ibexa:
    system:
        frontend_group:
            page_layout: "@ibexadesign/pagelayout.html.twig"
            user:
                login_template: "@ibexadesign/user/login.html.twig"
            field_templates:
                - { template: "@ibexadesign/parts/content_fields.html.twig", priority: 5000 }

netgen_tags:
    system:
        frontend_group:
            tag_view:
                template: "@ibexadesign/tag/view.html.twig"
                related_content_list:
                    limit: 6
                    return_content_info: false
