netgen_information_collection:
    system:
        default:
            action_config:
                email:
                    templates:
                        default: "@ibexadesign/info_collection/email.html.twig"
                    default_variables:
                        sender: "%collected_info_sender%"
                        recipient: "%collected_info_recipient%"
            actions:
                default:
                    - database
                    - email
